"""Download and stage the healthcare datasets (Day 1, KAN-11).

Fetches the two commercially-licensed datasets the sprint uses, writes them to
data/raw/ untouched, records provenance in SOURCES.md, and checksums everything.

    python scripts/download_data.py

data/raw/ is the reproducibility anchor for the whole sprint. This script writes
it once and refuses to overwrite unless --force is passed.

Licences verified 17 Aug 2026:
  MedMCQA   apache-2.0  — commercial use permitted
  PubMedQA  MIT         — commercial use permitted

Deliberately NOT included:
  ChatDoctor  no stated licence — unacceptable for a commercial POC
  MedQuAD     CC BY-SA 4.0 share-alike — may encumber derived models
"""

import argparse
import hashlib
import json
import sys
from datetime import date
from pathlib import Path

RAW = Path("data/raw")

DATASETS = {
    "medmcqa": {
        "hf_id": "openlifescienceai/medmcqa",
        "config": None,
        "splits": ["train", "validation"],
        "license": "apache-2.0",
        "url": "https://huggingface.co/datasets/openlifescienceai/medmcqa",
        "note": "182k medical MCQs, 21 subjects, with expert explanations (exp field)",
    },
    "pubmedqa": {
        "hf_id": "qiaojin/PubMedQA",
        "config": "pqa_labeled",
        "splits": ["train"],
        "license": "MIT",
        "url": "https://huggingface.co/datasets/qiaojin/PubMedQA",
        # The context field is why this dataset matters beyond v1: it gives real
        # retrieved-passage structure for the RAG-aware v3 round on Day 7.
        "note": "1k expert-labeled QA with abstract context — source of real context for v3",
    },
}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def download(name: str, spec: dict, force: bool) -> dict:
    from datasets import load_dataset

    out_dir = RAW / name
    if out_dir.exists() and any(out_dir.iterdir()) and not force:
        print(f"  {name:<10} already present, skipping (--force to redownload)")
        return {}
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"  {name:<10} fetching {spec['hf_id']}...")
    counts = {}
    for split in spec["splits"]:
        ds = (
            load_dataset(spec["hf_id"], spec["config"], split=split)
            if spec["config"]
            else load_dataset(spec["hf_id"], split=split)
        )
        target = out_dir / f"{split}.jsonl"
        ds.to_json(target, orient="records", lines=True)
        counts[split] = len(ds)
        size_mb = target.stat().st_size / 1024**2
        print(f"  {'':<10}   {split:<12} {len(ds):>7,} rows  {size_mb:>7.1f} MB")

    (out_dir / "LICENSE.txt").write_text(
        f"{spec['hf_id']}\nLicense: {spec['license']}\nSource: {spec['url']}\n"
        f"Downloaded: {date.today().isoformat()}\n"
    )
    return counts


def count_rows(name: str) -> int:
    """Count staged rows from disk, so SOURCES.md is right even on a skip-run."""
    total = 0
    for f in (RAW / name).glob("*.jsonl"):
        with f.open() as fh:
            total += sum(1 for _ in fh)
    return total


def write_sources(results: dict):
    """Rewrite SOURCES.md with what is actually staged on disk."""
    lines = [
        "# Dataset Sources",
        "",
        "Provenance for everything in `data/raw/`. Generated by",
        "`scripts/download_data.py` — licences verified against the dataset pages",
        "on the download date.",
        "",
        "| Dataset | Source | Licence | Rows | Downloaded | Notes |",
        "|---|---|---|---|---|---|",
    ]
    for name, spec in DATASETS.items():
        total = count_rows(name)
        rows = f"{total:,}" if total else "—"
        lines.append(
            f"| {name} | [{spec['hf_id']}]({spec['url']}) | `{spec['license']}` | "
            f"{rows} | {date.today().isoformat()} | {spec['note']} |"
        )

    lines += [
        "",
        "## Licence check",
        "",
        "Both datasets carry permissive licences allowing commercial use, which this",
        "POC requires.",
        "",
        "- [x] Commercial use permitted — Apache-2.0 and MIT both allow it",
        "- [x] Redistribution terms understood — attribution required, no share-alike",
        "- [x] Attribution recorded — see the table above and each `LICENSE.txt`",
        "- [x] No PHI — both are published research datasets, already de-identified",
        "",
        "## Deliberately excluded",
        "",
        "| Dataset | Why not |",
        "|---|---|",
        "| ChatDoctor-HealthCareMagic-100k | No stated licence. Attractive data (112k real "
        "patient–doctor exchanges) but unusable for a commercial POC without terms. |",
        "| MedQuAD | CC BY-SA 4.0. Share-alike may encumber derived model weights. Needs a "
        "legal decision before use. |",
        "",
        "If either is cleared by legal later, add it in a v2+ round rather than",
        "retrofitting v1 — the baseline must stay reproducible.",
        "",
        "## Integrity",
        "",
        "`CHECKSUMS.txt` is written at download time. Re-verify at any point:",
        "",
        "```bash",
        "python scripts/download_data.py --verify",
        "```",
        "",
        "A mismatch means the raw anchor changed and v1 is no longer reproducible.",
        "",
    ]
    (RAW / "SOURCES.md").write_text("\n".join(lines))


def write_checksums():
    files = sorted(
        p for p in RAW.rglob("*")
        if p.is_file() and p.name not in {"CHECKSUMS.txt", "SOURCES.md", ".gitkeep"}
    )
    lines = [f"{sha256(p)}  {p.relative_to(RAW)}" for p in files]
    (RAW / "CHECKSUMS.txt").write_text("\n".join(lines) + "\n")
    print(f"\n  checksummed {len(files)} files -> data/raw/CHECKSUMS.txt")


def verify() -> int:
    manifest = RAW / "CHECKSUMS.txt"
    if not manifest.exists():
        print("no CHECKSUMS.txt — run the download first")
        return 1

    bad = 0
    for line in manifest.read_text().splitlines():
        if not line.strip():
            continue
        want, rel = line.split("  ", 1)
        path = RAW / rel
        if not path.exists():
            print(f"  MISSING  {rel}")
            bad += 1
        elif sha256(path) != want:
            print(f"  CHANGED  {rel}")
            bad += 1

    if bad:
        print(f"\n{bad} file(s) differ. The raw anchor changed — v1 is not reproducible.")
        return 1
    print("  all files match — raw data intact")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--force", action="store_true", help="redownload even if present")
    ap.add_argument("--verify", action="store_true", help="check files against CHECKSUMS.txt")
    args = ap.parse_args()

    RAW.mkdir(parents=True, exist_ok=True)

    if args.verify:
        return verify()

    print("Downloading healthcare datasets\n")
    results = {}
    for name, spec in DATASETS.items():
        try:
            counts = download(name, spec, args.force)
            if counts:
                results[name] = counts
        except Exception as exc:  # noqa: BLE001 - report and continue to the next
            print(f"  {name:<10} FAILED: {type(exc).__name__}: {exc}")

    if not results and not args.force:
        print("\nNothing new downloaded.")

    write_sources(results)
    write_checksums()

    total = sum(sum(c.values()) for c in results.values())
    print(f"\nDone. {total:,} rows staged in data/raw/")
    print("Provenance written to data/raw/SOURCES.md")
    print("\nReminder: data/raw/ is read-only for the rest of the sprint.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
